Schoolpr/prjsch/prjsch/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("schsite.url"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = 'schsite.views.err404'

Schoolpr/prjsch/schsite/models.py
from django.db import models
from datetime import date
from django.urls import reverse
from django.conf import settings

# Create your models here.

class Klass(models.Model):
    klass = models.CharField("Класс", max_length=100, default=5)
    def __str__(self):
        return self.klass
    class Meta:
        verbose_name = "Класс"
        verbose_name_plural = "Классы"
class Items(models.Model):
    title = models.CharField("Название предмета", max_length=100)
    predmet = models.ManyToManyField(Klass, verbose_name="Предметы", blank=True)
    url = models.CharField("Название предмета на Англ", max_length=100, default='I dont know')
    def __str__(self) :
        return self.title
    class Meta:
        verbose_name = "Предмет"
        verbose_name_plural = "Предметы"
class Teachers(models.Model):
    image = models.ImageField("Изоброжение",upload_to='media', blank=True) 
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )
    it = models.ManyToManyField(Items, verbose_name='Предмет' , null=True)
    def __str__(self) :
        return self.author.username
    class Meta:
        verbose_name = "Учитель"
        verbose_name_plural = "Учителя"
class Students(models.Model):
    image = models.ImageField("Изоброжение",upload_to='media', blank=True) 
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )
    klas = models.ForeignKey(Klass, verbose_name="Класс", on_delete=models.SET_NULL, null=True)
    item = models.ManyToManyField(Items, verbose_name="Предметы", blank=True)
    def __str__(self):
        return self.author.username
    class Meta:
        verbose_name = "Ученик"
        verbose_name_plural = "Ученики"



class kolUrok(models.Model):
    title = models.CharField("Название Урока", max_length=100)
    data = models.DateField("Время задания", default=date.today)
    sdacha = models.DateField("Время сдачи", default=date.today)
    homework = models.CharField("Домашнее задание", max_length=100, blank=True)
    imgwork = models.ImageField("Изоброжение дз",upload_to='media', blank=True)
    genres = models.ManyToManyField(Students, verbose_name="Пресудствующие ученики", blank=True)
    item = models.ForeignKey(Items, verbose_name="Предмет", on_delete=models.CASCADE)
    nomer = models.PositiveIntegerField("Номер Урока", default="", blank=True)
    def __str__(self) :
        return self.item.title + " Урок № " + str(self.nomer)
    class Meta:
        abstract = False
        verbose_name = "Урок"
        verbose_name_plural = "Уроки"
class Password1(models.Model):
    password = models.CharField("Пороль, минимум 8 символов", max_length=20)
    def __str__(self) :
        return self.password
    class Meta:
        verbose_name = "пороль"
        verbose_name_plural = "пороли"

Schoolpr/prjsch/schsite/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView
from django.views.generic.base import View
from .models import Students,Teachers,Items,kolUrok, Klass,Password1
from django.contrib.auth.models import User
from  django.contrib.auth import authenticate
from  django.contrib.auth import login
from  django.contrib.auth import logout
from django.http import HttpResponse
from django.contrib.auth import get_user
from django.contrib.auth.models import AbstractBaseUser



# Create your views here.
class GenreView:
    def getGenres(self):
        return Students.objects.all()
    def getGenr(self):
        return User.objects.all()
def logout_view(request):
    logout(request)
    return redirect("profile")
class login_view(View):
    """Отзывы"""
    def post(self, request):
        user = authenticate(request, username=self.request.POST.get("name"), password=self.request.POST.get("password"))
        if user is not None:
            login(request, user)
        else:
            HttpResponse("У вас тут пусто")
        return redirect('profile') 
def main(request):
    return render(request, 'schsite/main.html')
def err404(request, exception):
    return render(request, 'schsite/err404.html')
def logView(request):
    return render(request, 'schsite/login.html')

class regStud(GenreView ,ListView):
    model = Students
    queryset = Students.objects.all()
    template_name = "schsite/students.html"
    context_object_name = 'users'
class AddReview(View):
    """Отзывы"""
    def post(self, request):
        stud = User(username=self.request.POST.get("name"))
        stud.set_password(self.request.POST.get("password")) 
        stud.is_active = False
        stud.save()
        login(request, stud, backend='django.contrib.auth.backends.ModelBackend')
        item1 = Items.objects.all()
        stud2 = Klass.objects.get(klass=self.request.POST.get("klas"))
        stud1 = Students(image=self.request.FILES.get("img"), author=stud, klas=stud2) 
        stud1.save()
        for itm in item1:
            stud1.item.add(itm)
        stud1.save()
        return redirect('/')
class UrokAdd(View):
    """Отзывы"""
    def post(self, request):
        tud2 = Items.objects.get(title=self.request.POST.get("predmet[]"))
        stu = kolUrok.objects.create(title=self.request.POST.get("tema"), data=self.request.POST.get("date"), sdacha=self.request.POST.get("date1"), homework=self.request.POST.get("dom"), item=tud2, nomer=self.request.POST.get("nomer"))   
        a = self.request.POST.getlist("man[]")
        for t in a:
            print(t)
        try:
            for t in a:
                tud3 = Students.objects.get(id=t)
                stu.genres.add(tud3)
        except:
            tud3 = Students.objects.get(id=self.request.POST.getlist("man[]"))
            stu.genres.add(tud3)
        return redirect('/')
class AddPassword(View):
    """Отзывы"""
    def get(self, request):
        a = self.request.GET.get("pas")
        s = Password1.objects.get(0)
        print(s)
        if str(s) == a: 
            return redirect('/')
        else:
            return redirect("/profile")
class Profile(GenreView,View):
    def get(self, request):
        queryset = User.objects.all()
        return render(request, 'schsite/profile.html',{'student': queryset})
class Urok(GenreView,View):
    def get(self, request, slug):
        kalm = Items.objects.get(url=slug)
        return render(request, 'schsite/urok.html', {'urok': kalm})
class DetaUrok(GenreView,View):
    def get(self,request, slug, pk):
        klm = Items.objects.get(url=slug)
        kalm = kolUrok.objects.get(id=pk)
        return render(request, 'schsite/detaurok.html', {'urok': kalm})
def password(request):
    return render(request, "schsite/password.html")
class AddUrok(GenreView ,ListView):
    model = Teachers
    queryset = User.objects.all()
    template_name = "schsite/addUrok.html"
    context_object_name = 'users'

    

Schoolpr/prjsch/schsite/templates/include/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="/">Home <span class="sr-only"></span></a>
        </li>
        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="/logout">Выйти</a>
        </li>
        {% endif %}
        <li class="nav-item dropdown">
          {% if user.is_authenticated == False %} 
          <a class="nav-link " href="profile/regStud" id="navbarDropdown" role="button"  >
            Register
          </a>
          {% endif %}
          </li>
          {% if user.is_authenticated == False %} 
          <li>
          <a class="nav-link " href="profile/login/" id="navbarDropdown" role="button"  >
            login
          </a>
          </li>
          {% endif %}
          {% if user.is_authenticated %}
          <li>
            <a class="nav-link" href="profile">{{user.username}}</a>
          </li>
          {% for st in student %}
          {% if st.username == user.username %}
          {% for car in st.students_set.all %}
          {% if car.image %}
          
          <li>
          <img class="nav-link" src="{{car.image.url}}" alt="" width="50" height="50" id="navbarDropdown" style="border-radius: 100px; border: lightgray solid 1px;">
          </li>
          {% else %}
          <li>
            <img src="../../static/schsite/150-1503945_transparent-user-png-default-user-image-png-png.png" alt="" width="50px" height="45px">
          </li>
          {% endif %}
          <li>
            <a class="nav-link" href="profile">Класс {{car.klas.klass}}</a>
          </li>
          {% endfor %}
          {% for cr in st.teachers_set.all %}
          {% if cr.image %}
          <li>
            <img src="{{cr.image.url}}" alt="" width="50px" height="50px" style="border-radius: 100px; border: lightgray solid 1px;">
          </li>
          {% else %}
          <li>
            <img src="../../static/schsite/150-1503945_transparent-user-png-default-user-image-png-png.png" alt="" width="50px" height="45px">
          </li>
          {% endif %}
          <li>
            <a class="nav-link " href="profile/addUrok" id="navbarDropdown" role="button"  >
              Добавить Дз
            </a>
          </li>
          {% endfor %}
          {% endif %}
          {% endfor %}
          {% endif %}



      </ul>
    </div>
  </nav>

Schoolpr/prjsch/schsite/templates/schsite/addUrok.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <title>Document</title>
</head>
<body>
    {% for s in users %}
    {% for i in s.teachers_set.all %}
    {% if user.username == i.author.username %}
    <h2 style="margin: 1%;">Добавление Домашнего задания</h2>
    <form action="{% url 'addUrok'  %}" method="POST" class="row g-3 needs-validation" novalidate>
        {% csrf_token %}
        <div class="col-md-4">
          <label for="validationCustom01" class="form-label">Тема урока</label>
          <input type="text" class="form-control" id="validationCustom01"  required name="tema">
          <div class="valid-feedback">
            Looks good!
          </div>
        </div>
        <div class="col-md-4">
          <label for="validationCustom02" class="form-label">Домашние задание</label>
          <input type="text" class="form-control" id="validationCustom02"  required name="dom">
          <div class="valid-feedback">
            Looks good!
          </div>
        </div>
        <div class="col-md-4">
          <label for="validationCustomUsername" class="form-label">Врема задания</label>
          <div class="input-group has-validation">
            <span class="input-group-text" id="inputGroupPrepend">&#9200;</span>
            <input type="date" class="form-control" id="validationCustomUsername" aria-describedby="inputGroupPrepend" required name="date">
            <div class="invalid-feedback">
              пожлуйста ведите дату.
            </div>
          </div>
        </div>
        <div class="col-md-4">
            <label for="validationCustomUsername" class="form-label">Врема сдачи</label>
            <div class="input-group has-validation">
              <span class="input-group-text" id="inputGroupPrepend">&#9200;</span>
              <input type="date" class="form-control" id="validationCustomUsername" aria-describedby="inputGroupPrepend" required name="date1">
              <div class="invalid-feedback">
                пожлуйста ведите дату.
              </div>
            </div>
          </div>
        <div class="col-md-6">
          <label for="validationCustom03" class="form-label">Номер урока</label>
          <input type="text" class="form-control" id="validationCustom03" required name="nomer">
          <div class="invalid-feedback">
            пожлуйста ведите номер урока.
          </div>
        </div>
        <div class="col-md-3">
          <div class="form-group">
            <label for="exampleFormControlSelect2">Пресудствующие Ученики</label>
            <select multiple class="form-control" id="exampleFormControlSelect2" name="man[]">
                {% for categ in view.getGenres %}
                <option value="{{categ.id}}" >{{categ.author.username}}</option>
                {% endfor %}
            </select>
          </div>
          <div class="invalid-feedback">
            пожлуйста выберите пресудствующих учеников.
          </div>
        </div>
        <label for="exampleFormControlSelect1">Урок</label>
        <select class="form-control" id="exampleFormControlSelect1" name="predmet[]">
        {% if i.author.username == user.username %}
        {% for io in i.it.all %}
            <option value="{{io.title}}" >{{io.title}}</option>
        {% endfor %}
        {% endif %}
        </select>
        <div class="col-12">
          <button class="btn btn-primary" type="submit">Создать дз</button>
        </div>
      </form>
      {% endif %}
      {% endfor %}
      {% endfor %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.min.js" integrity="sha384-j0CNLUeiqtyaRmlzUHCPZ+Gy5fQu0dQ6eZ/xAww941Ai1SxSY+0EQqNXNE6DZiVc" crossorigin="anonymous"></script>
    <script>// Example starter JavaScript for disabling form submissions if there are invalid fields
        (function () {
          'use strict'
        
          // Fetch all the forms we want to apply custom Bootstrap validation styles to
          var forms = document.querySelectorAll('.needs-validation')
        
          // Loop over them and prevent submission
          Array.prototype.slice.call(forms)
            .forEach(function (form) {
              form.addEventListener('submit', function (event) {
                if (!form.checkValidity()) {
                  event.preventDefault()
                  event.stopPropagation()
                }
        
                form.classList.add('was-validated')
              }, false)
            })
        })()
        </script>
</body>
</html>

Schoolpr/prjsch/schsite/templates/schsite/detaurok.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <title>Document</title>
</head>
<body>
    {% include 'include/navbar.html' %}
    <div style="text-align: center;font-size: xx-large;font-weight: 5px;background-color: #0d6efd;color: white;font-family: Arial, Helvetica, sans-serif;margin-top: 5%;width: 60%;margin-left: 20%;margin-right: 20%;border-radius: 15px;">
        Урок номер: {{urok.nomer}} <br>
        Тема: {{urok.title}} <br>
        Домашние задание: {{urok.homework}} <br>
        Задано: {{urok.data}} <br>
        Сдача: {{urok.sdacha}} <br>
        Пресудствующие Ученики: {% for i in urok.genres.all %} {{i.author.username}}, {% endfor %}
    </div>
</body>
</html>

Schoolpr/prjsch/schsite/templates/schsite/err404.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <p style="margin-left: 10%;margin-top: 10%;font-size: xx-large;">Eror 404</p>
</body>
</html>

Schoolpr/prjsch/schsite/templates/schsite/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <title>Login</title>
</head>
<body>
    <h2>Авторизация</h2>
    <form action="{% url 'logn'  %}" method="post" >
        {% csrf_token %}
    <div class="input-group mb-3" style="margin-top: 3%;">
        <div class="input-group-prepend">
          <span class="input-group-text" id="basic-addon1" style="background-color: #0d6efd;color: snow;">name</span>
        </div>
        <input type="text" class="form-control" placeholder="Username" aria-label="Username" aria-describedby="basic-addon1" name="name">
      </div>
      <div class="input-group mb-3">
        <div class="input-group-prepend">
          <span class="input-group-text" id="basic-addon1" style="background-color: #0d6efd;color: snow;">password</span>
        </div>
        <input type="password" class="form-control" placeholder="Password" aria-label="Username" aria-describedby="basic-addon1" name="password">
      </div>
      <button type="submit" class="btn btn-primary">Login</button>
    </form>
</body>
</html>

Schoolpr/prjsch/schsite/templates/schsite/main.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'schsite/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'schsite/style.css' %}">
    <link
    rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"
    />
    <title>Document</title>
</head>
<body>
    <div class="anim" id="app">
    
    <button @click="button = !button" class="btn btn-outline-primary" value="">показать гиффики</button>
    <div style="position: absolute;z-index: 2;">
    <button v-if="button" @click="one" class="btn btn-primary btn-sm" style="z-index: 2;" id="one">гифф 1</button>
    <button v-if="button" @click="one1" class="btn btn-primary btn-sm" style="z-index: 2;" id="on">гифф 2</button>
    </div>
    <div style="text-align: center;">
        <img src="../../static/schsite/9Khl.gif" alt="" v-if="messag === '1'" class="resp animate__animated animate__fadeInLeft" style="z-index: 1;" width="600" height="400">
        <img src="../../static/schsite/aaaaa.gif" alt="" v-if="messag === '2'" class="resp animate__animated animate__fadeInLeft" width="600" height="auto">  
    </div>
    <div>
    <a href="/profile"  class="btn btn-outline-primary" style="width: 60%; margin-left: 20%; margin-top: 10px; margin-right: 20%;">Начать Обучение</a>
    </div>
    <div style="text-align: center;">
    <button @click="cls()" class="btn btn-outline-primary" style="font-size: x-large;margin-top: 3%;">...</button>
    </div>
    <div v-if="inf" style="margin-top: 3%;" class="diva animate__animated animate__fadeInLeft">
        <h2 style="color: white;margin-left: 20px;font-weight: bold;">Домашние задание</h2>
        <p style="color: white;margin-left: 40px;font-size: medium;font-weight: bold;">просмотр и редактироваие домашнего задания<br> учителем. удобный и простой интерфейс . <br> Не режет глаза множеством кнопок</p>
    </div>
    <div v-if="inf"  class="div animate__animated animate__fadeInRight" ref="clas">
        <h2 style="color: white;margin-left: 20px;font-weight: bold;">Домашние задание</h2>
        <p style="color: white;margin-left: 40px;font-size: medium;font-weight: bold;">просмотр и редактироваие домашнего задания<br> учителем. удобный и простой интерфейс . <br> Не режет глаза множеством кнопок</p>
    </div>

    <div v-if="inf"  class="diva animate__animated animate__fadeInLeft">
        <h2 style="color: white;margin-left: 20px;font-weight: bold;">Домашние задание</h2>
        <p style="color: white;margin-left: 40px;font-size: medium;font-weight: bold;">просмотр и редактироваие домашнего задания<br> учителем. удобный и простой интерфейс . <br> Не режет глаза множеством кнопок</p>
    </div>
    <div v-if="inf" class="animate__animated animate__zoomIn">
    <h2 style="margin-left: 45%; margin-top: 10%;">учителя</h2>
    
        <img src="../../static/schsite/Kiana.jpg" alt="" class="kiana animate__animated animate__zoomIn">
        <br>
        Борис Евген
    </div>
    </div>



<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/vue@2/dist/vue.js"></script>
<script src="js/wow.min.js"></script>
<script>
new WOW().init();
</script>
<script>

var app = new Vue({
    el: '#app',
    data: {
      info: 0,
      messag: "1",
      button: false,
      inf: false,
      clas: false,

    },
    methods: {
        cls() {
            this.inf = !this.inf  
              
        },
        one(){
            this.messag = '1';
            sessionStorage.setItem('test', this.messag);
        },
        one1(){
            this.messag = '2';
            sessionStorage.setItem('test', this.messag);
        }

    },
    mounted: function () {
        if (sessionStorage.getItem('test')) {
        this.messag = sessionStorage.getItem('test');       
    }
}

  })
</script>
  
</body>
</html>

Schoolpr/prjsch/schsite/templates/schsite/mine.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Document</title>
</head>
<body>

    <script>
if (navigator.geolocation) {
  console.log('Geolocation is supported!');
}
else {
  console.log('Geolocation is not supported for this Browser/OS version yet.');
}
    </script>
</body>
</html>

Schoolpr/prjsch/schsite/templates/schsite/password.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action="{% url 'teacher' %}" method="GET">
        {% csrf_token %}
    <div style="text-align: center;margin-top: 20%;">
        <h2>Пароль</h2>
        <p>Введите пороль чтобы пройти регистрацию учителя</p>
        <input type="text" name="pas">
        <br>
        <button type="submit" style="padding: 5px; color: white;background-color: #0d6efd;border: none;border-radius: 15px;margin-top: 1%;">Отправить</button>
    </div>
    </form>
</body>
</html>

Schoolpr/prjsch/schsite/templates/schsite/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <link
    rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"
    />
    <title>Document</title>
</head>
<body>
    {% include 'include/navbar.html' %}
<h2></h2>
<div style="text-align: center;margin-top: 3%;" class="">
    {% if user.is_authenticated %}
    {% for s in student %}
    {% for st in s.students_set.all  %}
    {% if s.username == user.username %}
    {% for it in st.item.all %}
        {% for klasses in it.predmet.all %}
        {% if st.klas.klass == klasses.klass %}
        <a href="profile/{% for okey in it.url %}{{okey}}{% endfor %}" class="btn btn-primary animate__animated animate__bounceIn" style="margin-left: 1%;margin-top: 1%;" >{{it.title}}</a>
        {% endif %}
        {% endfor %}
    {% endfor %}
    {% endif %}
    {% endfor %}
    {% endfor %}
    {% endif %}
    {% if user.is_authenticated %}
    {% for s in student %}
    {% for st in s.teachers_set.all  %}
    {% if s.username == user.username %}
        {% for it in st.it.all %}
        <a href="profile/{% for okey in it.url %}{{okey}}{% endfor %}" class="btn btn-primary animate__animated animate__bounceIn" style="margin-left: 1%;margin-top: 1%;" >{{it.title}}</a>
        {% endfor %}
    {% endif %}
    {% endfor %}
    {% endfor %}
    {% endif %}
</div>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js" integrity="sha384-SR1sx49pcuLnqZUnnPwx6FCym0wLsk5JZuNx2bPPENzswTNFaQU1RDvt3wT4gWFG" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.min.js" integrity="sha384-j0CNLUeiqtyaRmlzUHCPZ+Gy5fQu0dQ6eZ/xAww941Ai1SxSY+0EQqNXNE6DZiVc" crossorigin="anonymous"></script>
</body>
</html>

Schoolpr/prjsch/schsite/templates/schsite/urok.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <link
    rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"/>
    <title>Document</title>
</head>
<body>
    {% include 'include/navbar.html' %}
    {% if user.is_authenticated %}
    {% for ur in urok.kolurok_set.all %}
       <a href="{{request.get_full_path}}/{{ur.id}}" class="btn btn-primary btn-lg btn-block animate__animated animate__bounceIn" style="width: 100%;margin-top: 1%;">{{ur.item}} <br> Урок номер   {{ur.nomer}} <br> {{ur.title}}</a>

       {% endfor %}
    {% endif %}
</body>
</html>